### PR TITLE
Set up deckbuilder layout

### PR DESCRIPTION
**Pull request by huguenot412**
Adds a layout for deckbuilder using CSS Grid

image

### CODE REVIEW

**Comment by yharaskrik** [comment]
Looks like something funky happened with the hamburger menu section.

image

**Comment by huguenot412** [comment]
That is odd. Did you add anything into the menu or is that just how it rendered? It still looks normal on my end. Which browser are you using?

**Comment by huguenot412** [comment]
The height of the top bar should just be set by the height of its content.

**Comment by huguenot412** [comment]
I can't reproduce that but I'm happy to jump on a call to troubleshoot it. I would have to play around in the inspector to see what's causing it.

**Comment by yharaskrik** [comment]
im in firefox, was using the preview link the bot posted above, ill check th einspector out myself and see if i can figure out whats going on. No rush, will check it out later.

**Comment by huguenot412** [comment]
Fixed the top bar height issue. Not sure why the preview was rendering it that way, what I had before should have been fine, but this update is probably better in any case.

**Comment by yharaskrik** [comment]
LGTM!

**Pull request merged**
